### ISSUE TITLE
Message d'accueil

### ISSUE THREAD

**Issue by edno** [edno/kleis#33]
In gitlab by @ValentinGuerlesquin on Sep 10, 2016, 02:34

En tant que superadmin, je peux mettre a jour un message qui s'affiche sur la page d'accueil lorsqu'un utilisateur se connecte. Je peux faire une mise en forme de base de ce message (gras, italique, couleur ...) .

**Comment by edno** [comment]
@ValentinGuerlesquin, comment est-ce que ce message doit s'afficher ? est-ce que cela doit remplacer une des section actuelles disponible sur la page d'accueil ? ou en message flash (message temporaire qui disparait apres X secondes) ? ...

**Comment by edno** [comment]
Pour l'edition, je propose le format [CommonMark](http://commonmark.org/) (a.k.a. Markdown), puisqu'il y a un parser tout fait (https://github.com/GrahamCampbell/Laravel-Markdown).
Est-ce que ca serait suffisant ou il faut quelque chose plus UI?

**Comment by edno** [comment]
@ValentinGuerlesquin, est-ce que tu pourrais me donner une idee des messages a afficher? Cela m'aiderait a identifier la solution

**Comment by ValentinGuerlesquin** [comment]
Le message pourrait s'afficher entre le bloc "Bienvenue" et "Informations" sur la page d'accueil une fois connecté.

Exemple de "Message à l'affiche" : 

Veuillez vous assurer que les informations des comptes sont correctement renseignées (Nom, Prénom...). Nous serons obligé de désactiver les comptes ne disposant pas d'informations complètes

**Comment by edno** [comment]
Ajout d'une variable de configuration `KLEIS_ANNOUNCE` pour indiquer le fichier markdown a afficher (fichier doit être present sous `public/markdown`).
Un fichier `example.md` est disponible comme exemple, mais il est possible d'avoir plusieurs fichiers.
Si `KLEIS_ANNOUNCE` n'est pas renseigné, ou si le fichier n'existe pas alors la section **Annonce** n'est pas affichée.
Voila le resultat: https://drive.google.com/open?id=0B-bwxK90zgvoZTBNOUc5ZzI2QWM
