### ISSUE TITLE
icone / banniere

### ISSUE THREAD

**Issue by edno** [edno/kleis#34]
In gitlab by @ValentinGuerlesquin on Sep 10, 2016, 02:36

Dans l'arborescence du logiciel, je peux mettre un image qui, éventuellement en précisant son chemin dans le fichier de configuration, s'affichera sur la page de login, la page d'accueil (quand non connecté), et en haut de la barre des taches une fois connecté.

**Comment by edno** [comment]
@ValentinGuerlesquin, un exemple d'images ?

**Comment by ValentinGuerlesquin** [comment]
https://www.le-refuge.org/images/logo_site.png par exemple

**Comment by edno** [comment]
Exemples:
- Welcome Page: https://drive.google.com/open?id=0B-bwxK90zgvoVG1aTmR1MDFoWkE
- Other pages: https://drive.google.com/open?id=0B-bwxK90zgvoRU96M0NpYzVYeE0
